### ISSUE TITLE
Cannot add nuget package to Windows Phone 8.1 application

### ISSUE THREAD

**Issue by swellfr** [charri/Font-Awesome-WPF#7]
When I try to install the nuget package 4.3.0.2, I have this error:

Failed to add reference to 'PresentationCore'. Please make sure it is in the global assembly cache.

**Comment by charri** [comment]
I'm guessing the PresentationCore is not available for Windows Phone SDK, so that is why the error occurs.

As you can see from the screenshot below, the dll is used in several places so simply dereferencing won't help...

![image](https://cloud.githubusercontent.com/assets/5507128/6791735/b57f7500-d1b1-11e4-82e0-ac9d3ddda98c.png)

Have you tried using the following package instead? Haven't used it personally but might work. https://www.nuget.org/packages/FontAwesome.Portable/

**Comment by swellfr** [comment]
This package is not working, it is compiled in debug and cannot be deployed to store...

I'm finally using FontAwesome directly.

**Comment by charri** [comment]
:thumbsup:
